language: cpp

addons:
  apt:
    update: true
    packages:
      - make 
      - cmake-data
      - cmake
      - libnova-dev
      - curl

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make

