language: cpp

addons:
  apt:
    sources:
      - sourceline: 'ppa:mutlaqja/ppa'
      - ubuntu-toolchain-r-test
    update: true
    packages:
      - make 
      - cmake-data
      - cmake
      - libnova-dev
      - curl
      - libindi1
      - libindi-dev
      - g++-6

env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make

