language: cpp

addons:
  apt:
    sources:
      - sourceline: 'ppa:mutlaqja/ppa'
    update: true
    packages:
      - make 
      - cmake-data
      - cmake
      - libnova-dev
      - curl
      - libindi1

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make

